name: EggWarsCoreLobby
main: net.minemora.eggwarscore.EggWarsCoreLobby
version: 1.0.0
softdepend: [Vault,HolographicDisplays,ProtocolLib,UltraCosmetics]
commands:
   ewc:
      usage: /<command>
   rules:
      usage: /<command>
      aliases: [reglas]
   stats:
      usage: /<command>
      aliases: [estadisticas]
   tutorial:
      usage: /<command>