name: EggWarsCore
main: net.minemora.eggwarscore.EggWarsCore
version: 1.0.0
softdepend: [Vault,HolographicDisplays, ReportSystem]
commands:
   ewc:
      usage: /<command>
   leave:
      usage: /<command>
      aliases: [salir]
   join:
      usage: /<command>
      aliases: [jugar]
   debug:
      usage: /<command>
   stats:
      usage: /<command>
      aliases: [estadisticas]